import { CustomizationPillar, ProcessStep, ProductItem, ServiceItem } from './types';

export const COMPANY_INFO = {
  name: 'FATHER AND SONS ENTERPRISES',
  brandShort: 'FATHER & SONS',
  tagline: 'Anything You Want, We Create.',
  taglineSecondary: 'You Have The Brand. We Make The Clothes.',
  businessType: 'Garment Manufacturing & Customized Clothing Production',
  establishedYear: '2025',
  gstNumber: '09NUMPS4573M1ZA',
  moq: '50 Pieces',
  phone: '+91 7303179577',
  phoneClean: '7303179577',
  whatsappUrl: 'https://wa.me/917303179577',
  email: 'Shoukat124319@gmail.com',
  address: {
    line1: 'H66, H-Block, Sector 9',
    cityArea: 'Gautam Buddha Nagar, Noida',
    state: 'Uttar Pradesh',
    country: 'India',
    pincode: '201301',
    googleMapsUrl: 'https://maps.app.goo.gl/DwTPsrJLJWySVurP8',
  },
  marketplaces: {
    meesho: 'https://www.meesho.com/TwinStarClothing1?ms=2',
    flipkart: 'https://www.flipkart.com/father-sons-enterprises-women-ribbed-maroon-mini-short-dress/p/itm3a0be8af94a5b?pid=DREHN97BCHCPP6B9',
    amazon: 'https://www.amazon.in/s?rh=n%3A1571271031%2Cp_4%3ATrendy%2BEveryday%2BFashion&ref=bl_sl_s_ap_web_1571271031',
    indiamart: 'https://www.indiamart.com/company/273562166/?srsltid=AU7gw4Uuwhr29YS_oahZVNfXwvzhXx6ak6yoj5AXT_LvpllfFrVSKC05',
  },
};

export const PRODUCTS: ProductItem[] = [
  {
    id: 't-shirts',
    name: 'T-SHIRTS',
    description: 'Custom T-shirts manufactured according to your requirements.',
    category: 'Casual & Streetwear',
    highlights: ['Oversized & Drop-Shoulder', 'Classic Crew & V-Neck', 'Bio-Washed & Silicon Softened', 'High-Density Screen / DTF Print ready'],
    fabrics: ['100% Combed Cotton', 'Cotton Spandex', 'Supima / Terry', 'Polyester Blends'],
    recommendedGsm: '180 – 280 GSM',
    typicalMoq: 'Starts from 50 pcs / color',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'joggers',
    name: 'JOGGERS',
    description: 'Customized joggers and lowerwear tailored to exact fit and comfort standards.',
    category: 'Bottomwear & Loungewear',
    highlights: ['Cargo Pockets & Tactical Styling', 'Custom Elastic Ribbed Waistband', 'Branded Drawcords & Eyelets', 'Tapered & Baggy Street Silhouettes'],
    fabrics: ['French Terry', 'Cotton Fleece', 'Loopknit Cotton', 'Poly-Cotton Blends'],
    recommendedGsm: '260 – 340 GSM',
    typicalMoq: 'Starts from 50 pcs',
    image: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'track-pants',
    name: 'TRACK PANTS',
    description: 'Custom track pants for brands and businesses, built for movement and durability.',
    category: 'Athleisure & Dailywear',
    highlights: ['Contrast Side Piping / Panels', 'Concealed Zipper Pockets', 'Anti-Static & Breathable', 'Reinforced Crotch & Inseam Stitching'],
    fabrics: ['NS Lycra 4-Way Stretch', 'Micro Polyester', 'Dry-Fit Interlock', 'Cotton Lycra'],
    recommendedGsm: '160 – 240 GSM',
    typicalMoq: 'Starts from 50 pcs',
    image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'sweatshirts',
    name: 'SWEATSHIRTS',
    description: 'Customized sweatshirt production with refined stitchwork and cozy handfeel.',
    category: 'Winterwear & Casuals',
    highlights: ['Drop-Shoulder Boxy Silhouette', 'Heavy Rib Hem & Cuffs', 'Custom Neck Tape & Woven Labels', 'Embroidery & Puff Print Compatible'],
    fabrics: ['3-Thread Heavy Fleece', 'Supercombed Loopknit', 'Brushed Terry Cotton', 'Thermal Melange'],
    recommendedGsm: '300 – 400 GSM',
    typicalMoq: 'Starts from 50 pcs',
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'hoodies',
    name: 'HOODIES',
    description: 'Custom hoodie manufacturing built for premium streetwear labels.',
    category: 'Premium Streetwear',
    highlights: ['Double-Layer Structured Hood', 'Seamless Kangaroo Pocket', 'Heavyweight Metal Aglets', 'Zip-Up & Pullover Formats'],
    fabrics: ['100% Cotton Heavy Terry', 'Fleece Lined', 'Poly-Cotton Brushed', 'Vintage Wash Cotton'],
    recommendedGsm: '330 – 450 GSM',
    typicalMoq: 'Starts from 50 pcs',
    image: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'gymwear',
    name: 'GYMWEAR',
    description: 'Customized activewear and gymwear engineered for athletic performance.',
    category: 'Active & Performance',
    highlights: ['Quick-Dry Moisture Wicking', 'Four-Way High Elasticity', 'Flatlock Ergonomic Seams', 'Anti-Odor & Breathable Treatment'],
    fabrics: ['Nylon Elastane / Spandex', 'Poly Lycra', 'Dry-Fit Micro Mesh', 'Interlock Knit'],
    recommendedGsm: '180 – 250 GSM',
    typicalMoq: 'Starts from 50 pcs',
    image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'custom-garments',
    name: 'CUSTOM GARMENTS',
    description: 'Have a different garment requirement? Discuss your design with us.',
    category: 'Specialty & Made-to-Spec',
    highlights: ['Bespoke Tech-Pack Realization', 'Custom Pattern Development', 'Unique Silhouette Crafting', 'End-to-End Material Sourcing'],
    fabrics: ['Woven, Knits, Ribs, Denims & Blends', 'Sourced on demand'],
    recommendedGsm: 'Customized to spec',
    typicalMoq: 'Starts from 50 pcs',
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=900&q=80',
  },
];

export const SERVICES: ServiceItem[] = [
  {
    id: 'pattern-making',
    number: '01',
    title: 'PATTERN MAKING',
    tag: 'Precision Engineering',
    description: 'Garment patterns created according to the required measurements and design.',
    features: [
      'Graded size charts (XS to 5XL)',
      'Custom measurement sheets & fit testing',
      'Digital CAD patterns ready for master cutting',
      'Silhouette balancing for streetwear & activewear',
    ],
  },
  {
    id: 'sampling',
    number: '02',
    title: 'SAMPLING',
    tag: 'Quality Gate',
    description: 'Create samples before production to review design, fitting and construction.',
    features: [
      'Pre-production prototype generation',
      'Stitch tension, seam strength & wash inspection',
      'Fabric drape and print accuracy testing',
      'Client revision and sign-off rounds',
    ],
  },
  {
    id: 'brand-manufacturing',
    number: '03',
    title: 'BRAND CLOTHING MANUFACTURING',
    tag: 'Private Label Ready',
    description: "Manufacture garments according to your brand's requirements.",
    features: [
      'Custom woven neck labels & care tags',
      'Hangtag attachment and barcode sticker placement',
      'Individual polybag packaging & export carton packing',
      'Strict quality checks (QC) on every single piece',
    ],
  },
  {
    id: 'custom-garment-manufacturing',
    number: '04',
    title: 'CUSTOM GARMENT MANUFACTURING',
    tag: 'Flexible Specs',
    description: 'Customized production based on design, measurements, fabric, color and other requirements.',
    features: [
      'Custom Pantone shade dyeing & acid/enzyme washes',
      'Screen printing, DTF, puff print & high-density embroidery',
      'Special trims, zippers, pullers & eyelets',
      'Low MOQ testing starting from 50 units',
    ],
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    step: '01',
    title: 'SHARE YOUR IDEA',
    description: 'Send your design, reference, tech pack or garment requirement.',
    detail: 'Share sketches, sample photos, mood boards, or physical references via WhatsApp or our inquiry form.',
  },
  {
    step: '02',
    title: 'PATTERN MAKING',
    description: 'Develop the required garment pattern.',
    detail: 'Our master pattern makers generate accurate cuts, armholes, collars, and graded size sets.',
  },
  {
    step: '03',
    title: 'SAMPLING',
    description: 'Create a sample for review.',
    detail: 'We stitch a complete pre-production prototype so you can test fabric feel, handfeel, and fitting.',
  },
  {
    step: '04',
    title: 'APPROVAL',
    description: 'Finalize the garment specifications.',
    detail: 'Any tweaks or sizing feedback are locked in before mass fabric cutting commences.',
  },
  {
    step: '05',
    title: 'PRODUCTION',
    description: 'Manufacture the approved garments.',
    detail: 'Our factory executes precision cutting, high-speed stitching, print/embroidery application, and multi-stage QC.',
  },
  {
    step: '06',
    title: 'FINISHED GARMENTS',
    description: 'Your customized garments are ready.',
    detail: 'Steam pressed, individual brand poly-packing, carton boxed, and dispatched securely to your doorstep.',
  },
];

export const BRAND_FEATURES = [
  { title: 'Custom Designs', description: 'Realize your graphic visions, cuts, and streetwear drops without creative compromise.' },
  { title: 'Custom Fit', description: 'Tailored oversized, boxy, relaxed, or athletic fits built to your exact spec sheets.' },
  { title: 'Custom Fabric', description: 'Knits, French terry, fleece, lycra, loopknit, and blends sourced directly from mills.' },
  { title: 'Custom Colors', description: 'From staple black & white to custom pantone hues, vintage washes, and dip-dyes.' },
  { title: 'Brand Manufacturing', description: 'Complete white-label solution with neck labels, wash tags, hang tags, and branded polybags.' },
  { title: 'Pattern Making', description: 'Industrial pattern drafting guaranteeing repeatable, consistent sizing across batches.' },
  { title: 'Sampling', description: 'Pre-bulk sample testing so you verify fit, fabric, and finishing before committing capital.' },
  { title: 'Bulk Production', description: 'Scaled production capacity backed by quality control and timely dispatches.' },
];

export const CUSTOMIZATION_PILLARS: CustomizationPillar[] = [
  {
    title: 'DESIGN',
    subtitle: 'Aesthetic & Blueprint',
    description: 'Manufacturing based on your design or reference.',
    examples: ['Streetwear silhouettes', 'Raglan & drop sleeves', 'Pockets & cut-and-sew panels', 'Hood & neckline variations'],
  },
  {
    title: 'FIT',
    subtitle: 'Measurement & Proportions',
    description: 'Measurements and fitting according to your requirements.',
    examples: ['True-to-size standard', 'Boxy streetwear oversized', 'Athletic muscle tapered', 'Crop and relaxed cuts'],
  },
  {
    title: 'FABRIC',
    subtitle: 'Material & Texture',
    description: 'Fabric requirements based on the garment.',
    examples: ['100% Combed Cotton (180–280 GSM)', 'French Terry (240–340 GSM)', 'Fleece & Loopknit (300–420 GSM)', 'Dry-Fit Lycra & Spandex'],
  },
  {
    title: 'COLOR',
    subtitle: 'Dyeing & Palettes',
    description: 'Custom color requirements.',
    examples: ['Pantone color matching', 'Reactive solid dyes', 'Acid wash & vintage stone wash', 'Melange & Heathered tones'],
  },
  {
    title: 'BRANDING',
    subtitle: 'Identity & Trims',
    description: 'Brand labels, logos and other branding requirements.',
    examples: ['Woven neck labels', 'Printed satin wash-care labels', 'Cardstock hang tags & strings', 'Custom embossed polybags'],
  },
  {
    title: 'DETAILS',
    subtitle: 'Trims & Hardware',
    description: 'Other garment details according to production feasibility.',
    examples: ['Custom metal drawcord tips', 'YKK / reverse coil zippers', 'Heavy 2x2 ribbing cuffs', 'Flatlock & safety overlock seams'],
  },
];
